'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Brain, FileText, LayoutDashboard, GitBranch, Code, Rocket, Play, AlignLeft, Download } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import pako from 'pako';
import { motion } from 'framer-motion';

import { ReactFlowCanvas } from '@/components/features/editors/ReactFlowCanvas';
import { LivePreviewIframe } from '@/components/features/editors/LivePreviewIframe';

import { DynamicUIBuilder } from '@/components/DynamicUIBuilder';

export default function SharePage() {
  const { id } = useParams();
  const [project, setProject] = useState<any>(null);
  const [activeTab, setActiveTab] = useState<string>("BRD");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchProject = async () => {
      try {
        const res = await fetch(`/api/share/${id}`);
        if (res.ok) {
          const data = await res.json();
          setProject(data);
          if (data.documents && data.documents.length > 0) {
            setActiveTab(data.documents[0].type);
          }
        }
      } catch (err) {
        console.error("Fetch error", err);
      } finally {
        setLoading(false);
      }
    };
    fetchProject();
  }, [id]);

  if (loading) return (
    <div className="h-screen bg-slate-950 flex flex-col items-center justify-center text-slate-400">
      <Brain className="w-12 h-12 animate-pulse mb-4 text-blue-500" />
      <p className="text-sm font-bold uppercase tracking-widest">Hydrating Shared Session...</p>
    </div>
  );

  if (!project) return (
    <div className="h-screen bg-slate-950 flex items-center justify-center text-slate-400">
      <p>Shared session not found or link expired.</p>
    </div>
  );

  const docs = project.documents.reduce((acc: any, doc: any) => {
    acc[doc.type] = doc.content;
    return acc;
  }, {});

  const currentDoc = docs[activeTab] || "";

  // Safely extract code if it was saved as a JSON string due to parse fallback
  let displayDoc = currentDoc;
  try {
    const jsonMatch = currentDoc.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      if (parsed.code) displayDoc = typeof parsed.code === 'string' ? parsed.code : JSON.stringify(parsed.code);
    }
  } catch(e) {}

  return (
    <div className="flex h-screen bg-[#0f172a] text-slate-200 overflow-hidden font-sans">
      <aside className="w-72 bg-[#1e293b]/80 border-r border-slate-700/50 backdrop-blur-xl flex flex-col shadow-2xl z-10">
        <div className="p-6 border-b border-slate-700/50 flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-blue-600 to-cyan-400 flex items-center justify-center shadow-lg">
            <Brain className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="font-bold text-lg text-white">BA Studio</h1>
            <p className="text-[10px] text-blue-400 font-bold uppercase tracking-widest">Shared Preview</p>
          </div>
        </div>
        <div className="p-4 overflow-y-auto flex-1">
          <h2 className="text-xs uppercase tracking-wider text-slate-500 font-semibold mb-3 px-2">Project Documents</h2>
          <nav className="space-y-1">
            {project.documents.map((doc: any) => (
              <button
                key={doc.type}
                onClick={() => setActiveTab(doc.type)}
                className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all text-sm ${activeTab === doc.type ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:bg-slate-800 hover:text-slate-200'}`}
              >
                <FileText className="w-4 h-4" />
                {doc.type}
              </button>
            ))}
          </nav>
        </div>
        <div className="p-6 border-t border-slate-700/50 text-center">
          <p className="text-[10px] text-slate-500 uppercase font-bold tracking-widest">Generated by Gaurav Nandhan</p>
        </div>
      </aside>

      <main className="flex-1 flex flex-col relative bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-[#1e293b] via-[#0f172a] to-[#0f172a]">
        <header className="h-16 border-b border-slate-700/30 flex items-center justify-between px-8 bg-[#0f172a]/50 backdrop-blur-md z-10">
          <h2 className="text-lg font-semibold text-slate-200 flex items-center gap-2">
             {project.title}
          </h2>
          <div className="px-4 py-1.5 bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 rounded-full text-[10px] font-bold uppercase tracking-widest">
            Read-Only Access
          </div>
        </header>

        <div className="flex-1 overflow-y-auto p-10">
          <div className="max-w-4xl mx-auto bg-[#1e293b]/50 backdrop-blur-xl border border-slate-700/50 p-10 rounded-3xl shadow-2xl">
            {(activeTab === "Wireframes" || activeTab === "Prototypes") ? (
               <div className="h-[600px]"><DynamicUIBuilder schema={displayDoc} isProcessing={false} /></div>
            ) : (activeTab === "Flowcharts" || activeTab === "UML Diagrams") ? (
               <div className="h-[600px] my-8 shadow-2xl rounded-3xl overflow-hidden border border-slate-700/50">
                 {(() => {
                    const match = currentDoc.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
                    const chartCode = match ? match[1].trim() : currentDoc.trim();
                    return <ReactFlowCanvas key={activeTab} chart={chartCode} />;
                 })()}
               </div>
            ) : (
              <div className="prose prose-invert prose-slate max-w-none">
                <ReactMarkdown 
                  remarkPlugins={[remarkGfm]}
                >
                  {currentDoc}
                </ReactMarkdown>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
