'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Brain, FileText, LayoutDashboard, GitBranch, Code, Rocket, Play, AlignLeft, Download } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import pako from 'pako';
import { motion } from 'framer-motion';

const MermaidRenderer = ({ chart }: { chart: string }) => {
  const [svg, setSvg] = useState<string>("");

  useEffect(() => {
    const render = async () => {
      try {
        const mermaid = (await import('mermaid')).default;
        mermaid.initialize({ startOnLoad: false, theme: 'dark' });
        const { svg } = await mermaid.render(`mermaid-${Math.random().toString(36).substr(2, 9)}`, chart);
        setSvg(svg);
      } catch (err) {
        console.error("Mermaid error", err);
      }
    };
    render();
  }, [chart]);

  return (
    <div className="bg-white p-6 rounded-xl flex justify-center overflow-x-auto shadow-inner border border-slate-700/30" dangerouslySetInnerHTML={{ __html: svg }} />
  );
};

export default function SharePage() {
  const { id } = useParams();
  const [project, setProject] = useState<any>(null);
  const [activeTab, setActiveTab] = useState<string>("BRD");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchProject = async () => {
      try {
        const res = await fetch(`/api/share/${id}`);
        if (res.ok) {
          const data = await res.json();
          setProject(data);
          if (data.documents && data.documents.length > 0) {
            setActiveTab(data.documents[0].type);
          }
        }
      } catch (err) {
        console.error("Fetch error", err);
      } finally {
        setLoading(false);
      }
    };
    fetchProject();
  }, [id]);

  if (loading) return (
    <div className="h-screen bg-slate-950 flex flex-col items-center justify-center text-slate-400">
      <Brain className="w-12 h-12 animate-pulse mb-4 text-blue-500" />
      <p className="text-sm font-bold uppercase tracking-widest">Hydrating Shared Session...</p>
    </div>
  );

  if (!project) return (
    <div className="h-screen bg-slate-950 flex items-center justify-center text-slate-400">
      <p>Shared session not found or link expired.</p>
    </div>
  );

  const docs = project.documents.reduce((acc: any, doc: any) => {
    acc[doc.type] = doc.content;
    return acc;
  }, {});

  const currentDoc = docs[activeTab] || "";

  return (
    <div className="flex h-screen bg-[#0f172a] text-slate-200 overflow-hidden font-sans">
      <aside className="w-72 bg-[#1e293b]/80 border-r border-slate-700/50 backdrop-blur-xl flex flex-col shadow-2xl z-10">
        <div className="p-6 border-b border-slate-700/50 flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-blue-600 to-cyan-400 flex items-center justify-center shadow-lg">
            <Brain className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="font-bold text-lg text-white">BA Studio</h1>
            <p className="text-[10px] text-blue-400 font-bold uppercase tracking-widest">Shared Preview</p>
          </div>
        </div>
        <div className="p-4 overflow-y-auto flex-1">
          <h2 className="text-xs uppercase tracking-wider text-slate-500 font-semibold mb-3 px-2">Project Documents</h2>
          <nav className="space-y-1">
            {project.documents.map((doc: any) => (
              <button
                key={doc.type}
                onClick={() => setActiveTab(doc.type)}
                className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all text-sm ${activeTab === doc.type ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:bg-slate-800 hover:text-slate-200'}`}
              >
                <FileText className="w-4 h-4" />
                {doc.type}
              </button>
            ))}
          </nav>
        </div>
        <div className="p-6 border-t border-slate-700/50 text-center">
          <p className="text-[10px] text-slate-500 uppercase font-bold tracking-widest">Generated by Gaurav Nandhan</p>
        </div>
      </aside>

      <main className="flex-1 flex flex-col relative bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-[#1e293b] via-[#0f172a] to-[#0f172a]">
        <header className="h-16 border-b border-slate-700/30 flex items-center justify-between px-8 bg-[#0f172a]/50 backdrop-blur-md z-10">
          <h2 className="text-lg font-semibold text-slate-200 flex items-center gap-2">
             {project.title}
          </h2>
          <div className="px-4 py-1.5 bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 rounded-full text-[10px] font-bold uppercase tracking-widest">
            Read-Only Access
          </div>
        </header>

        <div className="flex-1 overflow-y-auto p-10">
          <div className="max-w-4xl mx-auto bg-[#1e293b]/50 backdrop-blur-xl border border-slate-700/50 p-10 rounded-3xl shadow-2xl">
            {activeTab === "Prototypes" || activeTab === "Wireframes" ? (
               <iframe srcDoc={currentDoc} className="w-full h-[600px] bg-white rounded-xl border border-slate-700/50 shadow-2xl" />
            ) : (
              <div className="prose prose-invert prose-slate max-w-none">
                <ReactMarkdown 
                  remarkPlugins={[remarkGfm]}
                  components={{
                    code({inline, className, children, ...props}: any) {
                      const match = /language-(\w+)/.exec(className || '');
                      if (!inline && match && match[1] === 'mermaid') {
                        return <MermaidRenderer chart={String(children).replace(/\n$/, '')} />
                      }
                      if (!inline && match && match[1] === 'plantuml') {
                        const code = String(children).trim();
                        const data = new TextEncoder().encode(code);
                        const compressed = pako.deflate(data, { level: 9 });
                        const base64 = btoa(String.fromCharCode.apply(null, Array.from(compressed))).replace(/\+/g, '-').replace(/\//g, '_');
                        return (
                          <div className="bg-white p-6 rounded-xl flex justify-center shadow-xl border border-slate-700/30">
                            <img src={`https://kroki.io/plantuml/svg/${base64}`} alt="UML" className="max-w-full" />
                          </div>
                        );
                      }
                      return <code {...props}>{children}</code>
                    }
                  }}
                >
                  {currentDoc}
                </ReactMarkdown>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
